spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?useUnicode=true&characterEncoding=utf8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: ${DB_USER} # DB user
    password: ${DB_PASSWORD} # DB password
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
infra:
  job:
    key: ${JOB_API_KEY}
feign:
  client:
    config:
      default:
        logger-level: full

logging:
  level:
    root: debug